{{- $values := include "anycableGo.values" . | fromYaml }}
{{- with $values.hpa }}
{{- if .enabled }}
{{- $apiVersion := include "anycableGo.apiVersions.hpa" $ }}
---
apiVersion: {{ $apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "anycableGo.fullname" $ }}
  labels:
    app: {{ template "anycableGo.name" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "anycableGo.fullname" $ }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  {{- if eq $apiVersion "autoscaling/v1" }}
  targetCPUUtilizationPercentage: {{ .targetCPUUtilizationPercentage }}
  {{- else if eq $apiVersion "autoscaling/v2" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .targetCPUUtilizationPercentage }}
  {{- else }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}
{{- end }}
