{{- if .Values.image.pullSecrets.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "anycableGo.imagePullSecrets" . }}
kind: Secret
metadata:
  labels:
    app: {{ template "anycableGo.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: "{{ .Release.Name }}-docker-registry-secret"
type: kubernetes.io/dockerconfigjson
{{- end }}
