{{- $values := include "anycableGo.values" . | fromYaml }}
---
{{- if $values.image.pullSecrets.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "anycableGo.imagePullSecrets" $ }}
kind: Secret
metadata:
  labels: {{ include "anycableGo.labels" $ | nindent 4 }}
  name: "{{ $.Release.Name }}-docker-registry-secret"
type: kubernetes.io/dockerconfigjson
{{- end }}
