{{- $values := include "anycableGo.values" . | fromYaml }}
{{- if $values.ingress.enabled -}}
{{- range $values.ingress.tls }}
{{- if and .crt .key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels: {{ include "anycableGo.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .crt | b64enc | quote }}
  tls.key: {{ .key | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
