{{- $values := include "anycableGo.values" . | fromYaml }}
{{- range $host := ($values.ingress.nonAcme.hosts | default list) }}
  {{- if ($host.tls | and $host.tls.key | and $host.tls.crt) }}
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ $host.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $host.tls.crt | b64enc | quote }}
  tls.key: {{ $host.tls.key | b64enc | quote }}
  {{- end }}
{{- end }}
