{{- $values := include "anycableGo.values" . | fromYaml }}
{{- with ($values.ingress.nonAcme.hosts | default dict) }}
{{- if (.tls | and .tls.key | and .tls.crt) }}
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .tls.crt | b64enc | quote }}
  tls.key: {{ .tls.key | b64enc | quote }}
{{- end }}
{{- end }}
