{{- range $secret := .Values.ingress.nonAcme.hosts }}
{{- if $secret.tls }}
{{- if (and $secret.tls.key $secret.tls.crt) }}
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ $secret.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $secret.tls.crt | b64enc | quote }}
  tls.key: {{ $secret.tls.key | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
