{{- with .Values.pod.disruptionBudget -}}
{{- if .enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "anycableGo.fullname" $ }}
  labels:
    app: {{ template "anycableGo.name" $ }}
    component: anycable-go
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
spec:
  {{- if .minAvailable }}
  minAvailable: {{ .minAvailable }}
  {{- end }}
  {{- if .maxUnavailable }}
  maxUnavailable: {{ .maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "anycableGo.name" $ }}
      component: anycable-go
      release: {{ $.Release.Name | quote }}
{{- end -}}
{{- end }}
