{{- with .Values.pod.disruptionBudget -}}
{{- if .enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "anycableGo.fullname" $ }}
  labels: {{ include "anycableGo.labels" $ | nindent 4 }}
spec:
  {{- if .minAvailable }}
  minAvailable: {{ .minAvailable }}
  {{- end }}
  {{- if .maxUnavailable }}
  maxUnavailable: {{ .maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "anycableGo.name" $ }}
      component: anycable-go
      release: {{ $.Release.Name | quote }}
{{- end -}}
{{- end }}
