{{- $values := include "anycableGo.values" . | fromYaml }}
{{- $template := include "anycableGo.fullname" $ }}
{{- with $values.serviceMonitor }}
{{- if ($values.env.anycableMetricsPort | and .enabled) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $template }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    app: {{ $template }}
    component: anycable-go
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: {{ $.Release.Name | quote }}
    heritage: {{ $.Release.Service | quote }}
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      {{- if .interval }}
      interval: {{ .interval }}
      {{- end }}
  selector:
    matchLabels:
      app: {{ template "anycableGo.name" $ }}
      release: {{ $.Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
{{- end -}}
{{- end }}
