{{- if .Values.tls }}
{{- if (and .Values.tls.key .Values.tls.crt) }}
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.tls.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
{{- end }}
{{- end }}
