name: release-helm-chart
on:
  push:
    tags:
      - '*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repository
        name: Checkout anycable-helm
        uses: actions/checkout@v4
        with:
          path: anycable-helm/

      - id: setup-helm
        name: Setup Helm
        uses: azure/setup-helm@v3

      - id: prepare-gh-pages
        uses: actions/checkout@v4
        needs: checkout-repository
        with:
          path: helm-repository/
          ref: gh-pages

      - id: pack-chart-version
        name: Pack the current chart version
        needs:
          - checkout-repository
          - prepare-gh-pages
        run: helm package -d helm-repository/ anycable-helm/anycable-go/

      - id: reindex-helm-repository
        needs: pack-chart-version
        name: Reindex Helm repository
        run: helm repo index --url https://helm.anycable.net/ --merge helm-repository/index.yaml helm-repository/

      - name: Commit & Push gh-pages with a new chart
        needs: reindex-helm-repository
        run: |
          cd helm-repository/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Release all charts to gh-pages via 'make release'"
          git push origin gh-pages
