name: release-helm-chart
on:
  push:
    tags:
      - '*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout anycable-helm
        uses: actions/checkout@v4
        with:
          path: anycable-helm/

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - uses: actions/checkout@v4
        with:
          path: helm-repository/
          ref: gh-pages

      - name: Pack the current chart version
        run: helm package -d helm-repository/ anycable-helm/anycable-go/

      - name: Reindex Helm repository
        run: helm repo index --url https://helm.anycable.io/ --merge helm-repository/index.yaml helm-repository/

      - name: Commit & Push gh-pages with a new chart
        run: |
          cd helm-repository/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Release all charts to gh-pages via 'make release'"
          git push origin gh-pages
